services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=booking_user
      - POSTGRES_PASSWORD=booking_password
      - POSTGRES_DB=booking_db
    ports:
      - "5432:5432"

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=booking_db
      - DB_USER=booking_user
      - DB_PASSWORD=booking_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data:
